* README

Questo è un file di prova per vedere se github gestisce i file .org come i file .md

** Formattazione del testo

- *bold*
- /italic/
- _underline_
- +strike through+
- =code=
- ~commands~
- http://orgmode.org

: small example

** Tabella
| uno | due |
|-----|-----|
| cambo uno | campo due |
| altro | |
|12 | 24|

** Liste
- Uno
- Due
- [ ] Tre
- [x] Checked

1. Uno
2. Due
3. [ ] Tre
4. [X] Checked

** Code and others

*** Languages
#+BEGIN_SRC python
  name = input("Insert your name: ")
  print(f"Hello {name}")
#+END_SRC

#+BEGIN_SRC c++
  // Your First C++ Program

  #include <iostream>

  int main() {
      std::cout << "Hello World!";
      return 0;
  }
#+END_SRC

#+BEGIN_SRC sql
  CREATE TABLE students (name text, grade int);
  INSERT INTO students VALUES ("Eric", 83);
  INSERT INTO students VALUES ("John", 78);
  INSERT INTO students VALUES ("Andrew", 91);
  INSERT INTO students VALUES ("Jessica", 95);
  INSERT INTO students VALUES ("Chris", 79);
#+END_SRC

*** LaTeX

- Solo alcuni caratteri vengono renderizati  
  - Working outside of block: \alpha \beta \phi
  - not working: \LaTeX{}  $\varphi$
- Per il resto il LaTeX sembra non essere renderizzato

#+BEGIN_LATEX
\section{Section Title}

This is \emph{emphasized} and $y=x^2$ is an equation.

An example in an LATEX block.
Another line within this block.

\alpha $x=42y$

Greek characters \alpha \beta \phi \LaTeX{}  $\varphi$
#+END_LATEX

** Link
[[https://github.com/m0rp30/prova_org_readme/edit/main/README.org][This page!]]

[[https://picsum.photos/id/237/200/300][Foto di cane]]

I link, foto e documenti li gestisce tutti come link

** Commenti
#+BEGIN_COMMENT
This is a multi line comment block.
This is the second line.

This is the second paragraph.

This *is* an /example/ of _some_ syntax +highlighting+ within =links= and ~such~.
#+END_COMMENT

Sembra che non gestisca neanche i tag dei commenti

** Export info
#+TITLE: README
#+AUTHOR: luca canali
#+LANGUAGE: it

Qui non vedrete niente perché è una funzionalità per quando si esporta questo testo, provato solo su emacs
